spring.application.name=auth-service


spring.grpc.server.port=9090

spring.grpc.client.user-service.address=static://localhost:9091
spring.grpc.client.user-service.negotiation-type=plaintext

app.jwt.secret=${JWT_SECRET}