spring.application.name=auth-service


grpc.server.port=9093


grpc.client.user-service.address=static://localhost:9004
grpc.client.user-service.negotiationType=PLAINTEXT


app.jwt.secret=${JWT_SECRET}

