syntax = "proto3";

option java_package = "com.example.chat.user";
option java_multiple_files = true;

service MessageService {
  rpc SendMessage (SendMessageRequest) returns (MessageResponse);
  rpc GetChatHistory (ChatHistoryRequest) returns (ChatHistoryResponse);
  rpc DeleteMessage (DeleteMessageRequest) returns (DeleteMessageResponse);
}

message SendMessageRequest {
  string senderId = 1;
  string content = 2;
  string replyToMessageId = 3;

}

message MessageResponse {
  string messageId = 1;
  string senderId = 2;
  string content = 3;
  string createdAt = 4;
  string updatedAt = 5;
  string replyToMessageId = 6;
  bool isDeleted = 7;
}

message ChatHistoryRequest{
  string messageId = 1;
  string userId = 2;


}

message ChatHistoryResponse{
  repeated MessageResponse messages = 1;
  string responseId = 2;
  string username = 3;

}

message DeleteMessageRequest {
  string messageId = 2;
  string userId = 3;
}

message DeleteMessageResponse{
  bool success = 1;
  string messageId = 2;
  string userId = 3;

}