spring.application.name=message-service

server.port=8084

grpc.server.port=9005



spring.mongodb.password=${MONGO_PASSWORD:password123}

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
logging.level.org.mongodb.driver=DEBUG
