spring.application.name=bff-service
server.port=8091
grpc.client.auth-service.address=static://localhost:9093
grpc.client.auth-service.negotiation-type=plaintext

grpc.server.enabled=false
grpc.client.user-service.address=static://localhost:9004
grpc.client.user-service.negotiation-type=plaintext

grpc.client.message-service.address=static://localhost:9005
grpc.client.message-service.negotiation-type=plaintext

app.jwt.secret=${JWT_SECRET}

grpc.client.messageService.address=static://message-service:8089


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.docker.compose.enabled=false
