
spring.application.name=bff-service
server.port=8081


spring.grpc.client.user-service.address=static://localhost:9091
spring.grpc.client.user-service.negotiation-type=plaintext


spring.grpc.client.message-service.address=static://localhost:9092
spring.grpc.client.message-service.negotiation-type=plaintext


app.jwt.secret=${JWT_SECRET:UAZq4y/7yR26DXxFyqdevFWBRbAtTMkS2LywIclA2u0=}