
spring.application.name=bff-service
server.port=8089
grpc.client.auth-service.address=static://localhost:9093
grpc.client.auth-service.negotiation-type=plaintext

grpc.server.enabled=false
grpc.client.user-service.address=static://localhost:9004
grpc.client.user-service.negotiation-type=plaintext




app.jwt.secret=${JWT_SECRET}
