apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service
  labels:
    app: bot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-service
  template:
    metadata:
      labels:
        app: bot-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: bot-service
          image: bot-service:latest
          imagePullPolicy: Never

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: GRPC_SERVER_PORT
              value: "9098"
            - name: OPENROUTER_MODEL
              value: "openai/gpt-4o-mini"
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openrouter-secret
                  key: api-key

          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume

      volumes:
        - name: tmp-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  selector:
    app: bot-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8082