apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  labels:
    app: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: message-service
          image: message-service:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
          volumeMounts:
            - name: ephemeral-tmp
              mountPath: /tmp


          ports:
            - containerPort: 8085

          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"

            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongo-service:27017/messagedb"

            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password

            - name: SPRING_DOCKER_COMPOSE_ENABLED
              value: "false"

            - name: SPRING_MONGODB_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo-service:27017/messagedb?authSource=admin"
            - name: JWT_SECRET
              valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: secret

      volumes:
            - name: ephemeral-tmp
              emptyDir: { }





---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085